from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    opportunity_scout_report: Annotated[
        str, "Automated opportunity-routing report for selecting stocks and data lenses"
    ]
    stock_discovery_report: Annotated[
        str, "Pre-market 10-stock discovery report from the research department"
    ]
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # AI research department step
    current_news_report: Annotated[str, "Report from the Current News Scout"]
    strategy_report: Annotated[str, "Report from the Strategy Researcher"]
    copy_trading_report: Annotated[str, "Report from the Copy Trading Researcher"]
    github_research_report: Annotated[str, "Report from the GitHub Researcher"]
    research_department_report: Annotated[str, "Combined AI research department brief"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    # business departments
    investment_committee_report: Annotated[str, "Investment Committee memo"]
    trading_desk_report: Annotated[str, "Trading Desk execution memo"]
    risk_office_report: Annotated[str, "Independent Risk Office memo"]
    portfolio_office_report: Annotated[str, "Portfolio Office allocation memo"]
    operations_compliance_report: Annotated[str, "Operations and Compliance audit memo"]
    evaluation_report: Annotated[str, "Evaluation Department learning memo"]
    training_development_report: Annotated[
        str, "Training and Development memo for upskilling each AI agent role"
    ]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]
    training_context: Annotated[
        str, "Recent Training and Development lessons injected at run start"
    ]
